#!/bin/bash
#------------------------------------------------
#      Linux softs install scripts by env
#      copyright https://devops.oshit.com/
#      author: meyer.cheng
#------------------------------------------------
# Mark：epel设置 
#------------------------------------------------
function check_epel()
{
	path_not_exists_action "${SETUP_DIR}/.epel_ivhed" "setup_epel"

	return $?
}

function setup_epel()
{
	echo_style_text "Starting init '${MAJOR_OS}${MAJOR_VERS}_64bit EPEL Repository'"

	bind_if_inputty "COUNTRY_CODE" "Please sure 'your country code'"

	echo_style_text "The final checked country code is ''${COUNTRY_CODE}''"
	
	if [ "${COUNTRY_CODE}" == "CN" ]; then
		cat >/etc/resolv.conf<<EOF
# Generated by linux-unity/common/${MAJOR_OS_LOWER}/epel.sh
search ${SYS_NAME}
nameserver 223.5.5.5
nameserver 180.76.76.76
EOF

		while_wget "--content-disposition https://mirrors.ustc.edu.cn/epel/epel-release-latest-${MAJOR_VERS}.noarch.rpm" "rpm -ivh epel-release-latest-${MAJOR_VERS}.noarch.rpm && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-${MAJOR_VERS} && rpm -e yum"
		
		#更改镜像为国内镜像
		#http://centos.ustc.edu.cn/
		#http://mirrors.aliyun.com/repo/Centos-${MAJOR_VERS}.repo
		# echo "Change repos to CN..."
		# local TMP_SETED_MIRRORS=`cat /etc/yum.repos.d/CentOS-Base.repo | grep 'mirror.centos.org'`
		# if [ -n "$TMP_SETED_MIRRORS" ]; then
		# 	if [ ! -f "/etc/yum.repos.d/CentOS-Base.repo.backup" ]; then
		# 		mv /etc/yum.repos.d/CentOS-Base.repo /tmp/CentOS-Base.repo.backup
		# 		rm -rf /etc/yum.repos.d/*
		# 		wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-${MAJOR_VERS}.repo
		# 		mv /tmp/CentOS-Base.repo.backup /etc/yum.repos.d/
		# 		echo "" >> /etc/yum.repos.d/CentOS-Base.repo
		# 		echo "# At "`date +%Y%m%d`" init" >> /etc/yum.repos.d/CentOS-Base.repo
		# 	fi
		# fi
				
		echo "Reseting yum rpms to CN-ustc.edu..."
		while_wget "--content-disposition http://mirrors.ustc.edu.cn/${MAJOR_OS_LOWER}/${MAJOR_VERS}/os/x86_64/Packages/yum-3.4.3-168.el${MAJOR_VERS}.${MAJOR_OS_LOWER}.noarch.rpm" "rpm -ivh yum-3.4.3-168.el${MAJOR_VERS}.${MAJOR_OS_LOWER}.noarch.rpm"
		while_wget "--content-disposition http://mirrors.ustc.edu.cn/${MAJOR_OS_LOWER}/${MAJOR_VERS}/os/x86_64/Packages/yum-metadata-parser-1.1.4-10.el${MAJOR_VERS}.x86_64.rpm" "rpm -ivh yum-metadata-parser-1.1.4-10.el${MAJOR_VERS}.x86_64.rpm"
		while_wget "--content-disposition http://mirrors.ustc.edu.cn/${MAJOR_OS_LOWER}/${MAJOR_VERS}/os/x86_64/Packages/yum-plugin-fastestmirror-1.1.31-54.el${MAJOR_VERS}_8.noarch.rpm" "rpm -ivh yum-plugin-fastestmirror-1.1.31-54.el${MAJOR_VERS}_8.noarch.rpm"


		# # 创建docker目录
		# mkdir -p /etc/docker
		# # 创建配置文件
		# tee /etc/docker/daemon.json <<-'EOF'
		# {
		# "registry-mirrors": ["https://registry.docker-cn.com"]
		# }
		# EOF
		# # 加载新的配置文件
		# systemctl daemon-reload
		# # 重启docker服务
		# systemctl restart docker
	else
		cat >/etc/resolv.conf<<EOF
# Generated by linux-unity/common/${MAJOR_OS_LOWER}/epel.sh
search ${SYS_NAME}
nameserver 8.8.8.8
nameserver 1.1.1.1
EOF

		while_wget "--content-disposition http://dl.fedoraproject.org/pub/epel/epel-release-latest-${MAJOR_VERS}.noarch.rpm" "rpm -ivh epel-release-latest-${MAJOR_VERS}.noarch.rpm"
		while_wget "--content-disposition http://rpms.famillecollet.com/enterprise/remi-release-${MAJOR_VERS}.rpm" "rpm -ivh remi-release-${MAJOR_VERS}.rpm"
	fi

	yum -y install epel-release

	echo "Clearing yum cache..."
	yum clean all
	yum makecache fast

	yum repolist
	yum -y install yum-priorities
	yum -y install yum-plugin-fastestmirror
	
	soft_yum_check_setup "jsawk"

	echo "don't remove" >> ${SETUP_DIR}/.epel_ivhed
	
	return $?
}

check_epel